# render.yaml - A Render Blueprint for the Blox Battles Application (v2 - Corrected)
# This version adheres to the official Render Blueprint specification.

# Define all PostgreSQL databases in this top-level 'databases' section.
databases:
  - name: blox-battles-db
    plan: starter      # From your paid plan
    region: oregon     # IMPORTANT: Use the same region for all services

# Define all other application services (web servers, static sites, etc.) here.
services:
  # ---------------------
  # 1. The Backend Web Service (Node.js/Express)
  # ---------------------
  - type: web
    name: blox-battles-backend
    env: node
    plan: starter
    region: oregon
    rootDir: ./backend
    # The build command remains the same.
    buildCommand: "npm install"
    # The preDeployCommand is the correct place for database migrations.
    # It runs after a successful build but before the new version goes live.
    preDeployCommand: "./setup-database.sh"
    # The start command remains the same.
    startCommand: "node server.js"
    # This path will be used by Render to verify your service has started successfully.
    healthCheckPath: /api/status
    envVars:
      # This correctly references the database defined in the 'databases' block above.
      - key: DATABASE_URL
        fromDatabase:
          name: blox-battles-db
          property: connectionString
      # This correctly references the URL of the frontend service defined below.
      - key: SERVER_URL
        fromService:
          type: static
          name: blox-battles-frontend
          property: url
      # --- SECRETS ---
      # These values will be entered securely in the Render dashboard on first deploy.
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BOT_API_KEY
        sync: false
      - key: ADMIN_TEST_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALCHEMY_POLYGON_URL
        sync: false
      - key: ALCHEMY_API_KEY
        sync: false
      - key: MASTER_XPUB
        sync: false
      - key: PAYOUT_WALLET_PRIVATE_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false

  # ---------------------
  # 2. The Frontend Static Site (React/Vite)
  # ---------------------
  - type: static
    name: blox-battles-frontend
    region: oregon
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    publishDir: ./dist
    # This rewrite rule is essential for React Router to work correctly.
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false

  # ---------------------
  # 3. The Cron Job
  # ---------------------
  - type: cron
    name: blox-battles-cron
    env: node
    region: oregon
    schedule: "*/1 * * * *" # Runs every minute
    # Ensure you have created this dedicated file for the cron job's logic.
    command: "node backend/cron-tasks.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blox-battles-db
          property: connectionString
