# render.yaml - A Render Blueprint for the Blox Battles Application (v7 - Production Routing)
# This version adds a production-grade API rewrite rule for the frontend.

databases:
  - name: blox-battles-db
    plan: basic-256mb
    region: oregon

services:
  # ---------------------
  # 1. The Backend Web Service (Node.js/Express)
  # ---------------------
  - type: web
    name: blox-battles-backend
    runtime: node
    plan: starter
    region: oregon
    rootDir: ./backend
    buildCommand: "npm install"
    preDeployCommand: "./setup-database.sh"
    startCommand: "node server.js"
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blox-battles-db
          property: connectionString
      - key: SERVER_URL # This is for CORS and frontend redirects
        value: https://blox-battles-frontend.onrender.com
      # [NEW] This is specifically for the Google OAuth callback URL.
      - key: BACKEND_URL
        value: https://blox-battles-backend.onrender.com
      # --- SECRETS (sync: false) ---
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BOT_API_KEY
        sync: false
      - key: ADMIN_TEST_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALCHEMY_POLYGON_URL
        sync: false
      - key: ALCHEMY_API_KEY
        sync: false
      - key: MASTER_XPUB
        sync: false
      - key: PAYOUT_WALLET_PRIVATE_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false

  # ---------------------
  # 2. The Frontend Static Site (React/Vite)
  # ---------------------
  - type: web
    name: blox-battles-frontend
    runtime: static
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /api/:path*
        destination: https://blox-battles-backend.onrender.com/api/:path*
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
      # This is still needed for the frontend to know where to link to for Google Auth.
      - key: VITE_API_BASE_URL
        value: https://blox-battles-backend.onrender.com

  # ---------------------
  # 3. The Cron Job
  # ---------------------
  - type: cron
    name: blox-battles-cron
    runtime: node
    region: oregon
    schedule: "*/1 * * * *"
    startCommand: "node backend/cron-tasks.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blox-battles-db
          property: connectionString
