# render.yaml - A Render Blueprint for the Blox Battles Application (v3 - Corrected)
# This version uses the correct type and runtime for the Static Site.

# Define all PostgreSQL databases in this top-level 'databases' section.
databases:
  - name: blox-battles-db
    plan: starter
    region: oregon

# Define all other application services (web servers, static sites, etc.) here.
services:
  # ---------------------
  # 1. The Backend Web Service (Node.js/Express)
  # ---------------------
  - type: web
    name: blox-battles-backend
    # 'env' is a valid but discouraged alias for 'runtime'. Let's use 'runtime'.
    runtime: node
    plan: starter
    region: oregon
    rootDir: ./backend
    buildCommand: "npm install"
    preDeployCommand: "./setup-database.sh"
    startCommand: "node server.js"
    healthCheckPath: /api/status
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blox-battles-db
          property: connectionString
      # This reference now correctly points to the 'web' type service named 'blox-battles-frontend'.
      - key: SERVER_URL
        fromService:
          type: web # The type of the service being referenced
          name: blox-battles-frontend
          property: url
      # --- SECRETS ---
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BOT_API_KEY
        sync: false
      - key: ADMIN_TEST_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ALCHEMY_POLYGON_URL
        sync: false
      - key: ALCHEMY_API_KEY
        sync: false
      - key: MASTER_XPUB
        sync: false
      - key: PAYOUT_WALLET_PRIVATE_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false

  # ---------------------
  # 2. The Frontend Static Site (React/Vite)
  # [CORRECTED] The 'type' must be 'web' and 'runtime' specifies it's a static site.
  # ---------------------
  - type: web # CORRECTED: The type for a static site is 'web'.
    name: blox-battles-frontend
    runtime: static # CORRECTED: This field specifies it's a static site.
    region: oregon
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    # 'staticPublishPath' is the correct key for the output directory.
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false

  # ---------------------
  # 3. The Cron Job
  # ---------------------
  - type: cron
    name: blox-battles-cron
    runtime: node
    region: oregon
    schedule: "*/1 * * * *"
    command: "node backend/cron-tasks.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blox-battles-db
          property: connectionString
